reasonable training time
mindsdb/mindsdb_native pull request #229
Opened 2020-10-12 06:36 UTC by maximlopin

2020-10-12 06:36 UTC, mindsdbadmin commented
****CLA Assistant Lite bot**** All contributors have signed the CLA  ✍️

2020-10-12 20:02 UTC, George3d6 requested changes

2020-10-12 20:02 UTC, George3d6 commented on mindsdb_native/libs/backends/lightwood.py
> +                elif reasonable_training_time / 10 > self.transaction.lmd['stop_training_in_x_seconds']:
Your debug flag comes in handy here, only do this in "debug" mode, aka when testing, but not when we release.

2020-10-12 20:02 UTC, George3d6 commented on mindsdb_native/libs/backends/lightwood.py
> +                elif reasonable_training_time / 10 > self.transaction.lmd['stop_training_in_x_seconds']:
Actually, probably better to just comment this out from now, and let's get back to it after the Precona release.

2020-10-12 20:02 UTC, George3d6 commented on mindsdb_native/libs/backends/lightwood.py
> +                        kwargs['stop_training_after_seconds'] = self.transaction.lmd['stop_training_in_x_seconds']
This logic should happen during the previous if/else chain when the mixers are selected

2020-10-12 20:08 UTC, George3d6 commented
Ok, since this needs to be deployed fast I went ahead and made all the changes, @maximlopin review tomorrow and let me know of what you think

2020-10-13 05:27 UTC, maximlopin commented
looks good

2020-10-13 08:09 UTC, merged