test/valid/train accuracy (WIP)
mindsdb/mindsdb_native pull request #45
Opened 2020-07-07 05:14 UTC by maximlopin

2020-07-07 09:25 UTC, btseytlin submitted a review, later dismissed
All great, just add a test, please

2020-07-07 22:54 UTC, maximlopin commented
@btseytlin will do

2020-07-08 11:03 UTC, George3d6 requested changes

2020-07-08 11:03 UTC, George3d6 commented on mindsdb_native/libs/phases/model_analyzer/model_analyzer.py
> +        self.transaction.lmd['valid_accuracy'] = {}
You need to modify `get_model_data` in order for these to be sent to `mindsdb` and then exposed via the http API

2020-07-08 21:53 UTC, George3d6 approved these changes

2020-07-08 21:53 UTC, George3d6 commented on mindsdb_native/libs/controllers/functional.py
> +
Perfect, added all of them in my mindsdb (server) PR so that we are exposing them to the GUI, go ahead and merge

2020-07-08 21:54 UTC, George3d6 approved these changes

2020-07-09 05:46 UTC, merged