Grouped conformal predictors
mindsdb/mindsdb_native pull request #460
Opened 2021-03-02 15:55 UTC by paxcema

## Why
Time series tasks with grouped-by columns had poor confidence estimation due to a single Inductive Conformal Predictor handling all data at once. For informative prediction bounds, we need to instance one ICP per each group combination.

## How
To avoid unnecessary reshaping, this PR generates and caches prediction results once for the complete model analysis phase (which can be disabled through a `df_cache` flag.

Regarding confidence estimation, helpers have been divided into conformal and generic confidence helpers. The procedure to calibrate ICPs in Model Analysis and the one in PredictTransaction to estimate confidence when querying have been restructured to handle the case of grouped time series.

### Notes
This is staying as a draft while benchmarks are finished and to clean up the code.

2021-03-08 20:19 UTC, paxcema commented on mindsdb_native/libs/phases/model_analyzer/model_analyzer.py
> +                        # add all predictions to the DF
move this up

2021-03-08 20:20 UTC, paxcema commented on mindsdb_native/libs/phases/model_analyzer/model_analyzer.py
> +                        for key, val in zip(group_keys, group):
check if mutable, might not be necessary

2021-03-08 20:27 UTC, George3d6 requested changes

2021-03-08 20:27 UTC, George3d6 commented on mindsdb_native/libs/phases/model_interface/lightwood_backend.py
> +                self.transaction.input_data.cached_train_df = run_df
cache that during the training phase.

2021-03-08 20:27 UTC, George3d6 commented on mindsdb_native/libs/phases/model_interface/lightwood_backend.py
> +                self.transaction.input_data.cached_test_df = run_df
cache that during the training phase.

2021-03-08 20:27 UTC, George3d6 commented on mindsdb_native/libs/phases/model_analyzer/model_analyzer.py
> +                            icp_df[f'__predicted_{target}'] = normal_predictions[target]
move before the for.

2021-03-08 20:27 UTC, George3d6 commented on mindsdb_native/libs/phases/model_analyzer/model_analyzer.py
> +                    ranges = result_df.values
Throw out these and also the code that prepares sample ts data for scout.

2021-03-09 17:16 UTC, paxcema commented
Handle non-grouped case with a `__default` to streamline the code in `ModelAnalysis` and `PredictTransaction`

2021-03-11 20:50 UTC, merged