Refactor datasource
mindsdb/mindsdb_native pull request #60
Opened 2020-07-11 21:27 UTC by maximlopin

- remove redundant `:param:` and `:return:` comments from docstrings
- add comments in `DataSource._cleanup` and `DataSource._setup` informing that they can be overriden
- make `DATA_TYPES_SUBTYPES ` a `dict`
- explicitly call `__getattr__`, `__getitem__`, `__setitem__` in `DataSource` when it maps them to the `DataFrame`
- fix a few for loops so it's easier to follow the logic
- remove test under `__name__ == '__main__'` in  `S3DS` datasource

2020-07-13 14:53 UTC, George3d6 requested changes
> add comments in DataSource._cleanup and DataSource._setup informing that they can be overriden

As discussed, just stick to `pass` and don't add the `Can be overriden by subclasses`, that should be the default for any method we have

> explicitly call __getattr__, __getitem__, __setitem__ in DataSource when it maps them to the DataFrame
Why ?

The rest of the changes look fine

2020-07-14 07:04 UTC, maximlopin commented
@George3d6 `__getitem__`-like methods are at level of abstraction below the `[]` operator, so calling `__getitem__` which is at the same level of abstraction makes more sense and is more explicit.

2020-07-14 10:27 UTC, George3d6 commented
Fair point. Go ahead and merge.

2020-07-14 10:27 UTC, George3d6 approved these changes

2020-07-14 11:25 UTC, merged