Multiple categories
mindsdb/mindsdb_native pull request #76
Opened 2020-07-17 13:23 UTC by btseytlin

2020-07-18 12:34 UTC, George3d6 requested changes
I know the PR is still WIP, but please try to separate everything that is not related to it (e.g. changes in where stuff is imported for the databases test) into a separate PR.

2020-07-18 12:34 UTC, George3d6 commented on tests/integration_tests/data_sources/test_clickhouse_ds.py
> +    from mindsdb_native.libs.data_sources.clickhouse_ds import ClickhouseDS
Is this related to this PR ?

2020-07-18 12:34 UTC, George3d6 commented on tests/integration_tests/data_sources/test_maria_ds.py
> +    from mindsdb_native import MariaDS
Is this related to this PR ?

2020-07-18 12:34 UTC, George3d6 commented on tests/integration_tests/data_sources/test_mongodb_ds.py
> +    from mindsdb_native.libs.data_sources.mongodb_ds import MongoDS
Is this related to this PR ?

2020-07-18 12:34 UTC, George3d6 commented on tests/integration_tests/data_sources/test_ms_sql_ds.py
> +    from mindsdb_native.libs.data_sources.ms_sql_ds import MSSQLDS
Is this related to this PR ?

2020-07-18 12:34 UTC, George3d6 commented on tests/integration_tests/data_sources/test_mysql_ds.py
> +    from mindsdb_native.libs.data_sources.mysql_ds import MySqlDS
Is this related to this PR ?

2020-07-18 12:34 UTC, George3d6 commented on tests/integration_tests/data_sources/test_postgres_ds.py
> +    from mindsdb_native.libs.data_sources.postgres_ds import PostgresDS
Is this related to this PR ?

2020-07-18 12:34 UTC, George3d6 commented on mindsdb_native/libs/phases/data_cleaner/data_cleaner.py
> +    def _convert_iterables_to_tuples(self, df):
Why is this required ?

2020-07-18 12:34 UTC, George3d6 commented on mindsdb_native/libs/phases/data_cleaner/data_cleaner.py
> +    def _convert_iterables_to_tuples(self, df):
As in, I assume this converts arrays into tuple, but why is this needed ?

2020-07-18 12:34 UTC, George3d6 commented on mindsdb_native/libs/phases/data_cleaner/data_cleaner.py
> +import numpy as np
unused

2020-07-29 16:10 UTC, maximlopin commented on mindsdb_native/libs/phases/data_cleaner/data_cleaner.py
> +           self._remove_duplicate_rows(df)
must be 4 spaces (in context of this `if` statement) before `self._remove_duplicate_rows(df)`

2020-07-29 16:19 UTC, maximlopin commented on mindsdb_native/libs/phases/type_deductor/type_deductor.py
> +                        additional_info['separator'] = sep_char
weird indentation again

2020-07-29 16:27 UTC, maximlopin approved these changes

2020-08-03 17:03 UTC, merged